export enum ActionTypes {
    // REQUEST
    REQUEST_HOME_PAGE_MODEL = "REQUEST_HOME_PAGE_MODEL",
    REQUEST_SERVICES = "REQUEST_SERVICES",
    REQUEST_WORKS = "REQUEST_WORKS",
    REQUEST_BLOG_POSTS = "REQUEST_BLOG_POSTS",
    REQUEST_BRANDS = "REQUEST_BRANDS",
    REQUEST_TESTIMONIALS = "REQUEST_TESTIMONIALS",
    REQUEST_AUTH = "REQUEST_AUTH",
    REQUEST_MESSAGES = "REQUEST_MESSAGES",
    REQUEST_CONTACTS = "REQUEST_CONTACTS",
    REQUEST_USERS = "REQUEST_USERS",

    // REQUEST_COMPLETED
    REQUEST_HOME_PAGE_MODEL_COMPLETED = "REQUEST_HOME_PAGE_MODEL_COMPLETED",
    REQUEST_SERVICES_COMPLETED = "REQUEST_SERVICES_COMPLETED",
    REQUEST_WORKS_COMPLETED = "REQUEST_WORKS_COMPLETED",
    REQUEST_BLOG_POSTS_COMPLETED = "REQUEST_BLOG_POSTS_COMPLETED",
    REQUEST_BRANDS_COMPLETED = "REQUEST_BRANDS_COMPLETED",
    REQUEST_TESTIMONIALS_COMPLETED = "REQUEST_TESTIMONIALS_COMPLETED",
    REQUEST_AUTH_COMPLETED = "REQUEST_AUTH_COMPLETED",
    REQUEST_MESSAGES_COMPLETED = "REQUEST_MESSAGES_COMPLETED",
    REQUEST_CONTACTS_COMPLETED = "REQUEST_CONTACTS_COMPLETED",
    REQUEST_USERS_COMPLETED = "REQUEST_USERS_COMPLETED",

    // APP
    INITIAL_APP_STATE = "INITIAL_APP_STATE",
    HOME_PAGE_MODEL = "HOME_PAGE_MODEL",
    ERROR = "ERROR",

    // NOTIFICATIONS
    ADDED_NOTIFICATION = "ADDED_NOTIFICATION",
    DELETED_NOTIFICATION = "DELETED_NOTIFICATION",

    // MESSAGES
    SENDING_RESULT = "SENDING_RESULT",
    MESSAGES = "MESSAGES",
    CURRENT_MESSAGE = "CURRENT_MESSAGE",

    // AUTH
    SIGN_IN = "SIGN_IN",
    SIGN_OUT = "SIGN_OUT",

    // BLOG
    BLOG_POSTS = "BLOG_POSTS",
    CURRENT_BLOG_POST = "CURRENT_BLOG_POST",

    // USERS
    USERS = "USERS",
    CURRENT_USER = "CURRENT_USER",

    // SERVICES
    SERVICES = "SERVICES",
    CURRENT_SERVICE = "CURRENT_SERVICE",

    // WORKS
    WORKS = "WORKS",
    CURRENT_WORK_EXAMPLE = "CURRENT_WORK_EXAMPLE",

    // BRANDS
    BRANDS = "BRANDS",
    CURRENT_BRAND = "CURRENT_BRAND",

    // TESTIMONIALS
    TESTIMONIALS = "TESTIMONIALS",
    CURRENT_TESTIMONIAL = "CURRENT_TESTIMONIAL",

    // CONTACTS
    CONTACTS = "CONTACTS"
}
